apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"cmbcluster-pod-manager"},"rules":[{"apiGroups":[""],"resources":["pods","pods/log","pods/status","services","persistentvolumeclaims","persistentvolumeclaims/status","persistentvolumes"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["apps"],"resources":["deployments","deployments/status","replicasets"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["networking.k8s.io"],"resources":["ingresses"],"verbs":["create","delete","get","list","patch","update","watch"]}]}
  creationTimestamp: "2025-06-30T07:31:44Z"
  name: cmbcluster-pod-manager
  resourceVersion: "1751268704469743016"
  uid: 66fc938a-f00f-4390-bb0a-361d0a734676
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/status
  - services
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/status
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
