services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    # Loads sensitive variables from the .env file in the project root
    env_file: .env
    environment:
      - DEV_MODE=true
      - DEBUG=true
      - MOCK_KUBERNETES=true
      - API_URL=http://localhost:8000
      - FRONTEND_URL=http://localhost:8501
    volumes:
      - ./backend:/app
      - ~/.kube:/root/.kube:ro
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - DEV_MODE=true
      - API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: unless-stopped

  user-env:
    build: ./user-environment
    ports:
      - "8502:8501"
    environment:
      - USER_ID=dev-user
      - USER_EMAIL=dev@cmbcluster.local
      - HUB_URL=http://backend:8000
    volumes:
      - ./user-environment:/app
    restart: unless-stopped

networks:
  default:
    name: cmbcluster-network
