apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cmbcluster.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmbcluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "cmbcluster.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "cmbcluster.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - name: nextjs
          containerPort: 8501
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8501"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: API_URL
          value: "https://api.{{ .Values.ingress.baseDomain }}"
        - name: BASE_DOMAIN
          value: "{{ .Values.ingress.baseDomain }}"
        - name: NEXTAUTH_URL
          value: "https://{{ .Values.ingress.baseDomain }}"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        - name: DEV_MODE
          value: "false"
        # Authentication secrets from the same secret as backend
        envFrom:
        - secretRef:
            name: {{ .Values.backend.secretName }}
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /api/health
            port: nextjs
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: nextjs
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
      volumes:
      - name: tmp-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmbcluster.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmbcluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: nextjs
    protocol: TCP
    name: nextjs
  selector:
    {{- include "cmbcluster.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
