{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cmbcluster.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmbcluster.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - "{{ .Values.global.domain }}"
    - "api.{{ .Values.global.domain }}"
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  # Frontend - main domain
  - host: "{{ .Values.global.domain }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "cmbcluster.frontend.fullname" . }}
            port:
              number: {{ .Values.frontend.service.port }}
  
  # API Backend - api subdomain
  - host: "api.{{ .Values.global.domain }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "cmbcluster.backend.fullname" . }}
            port:
              number: {{ .Values.backend.service.port }}
{{- end }}
