{{- if .Values.serviceAccount.create -}}
# Service Account for user-spawned pods.
# This account has no permissions by default, following the principle of least privilege.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.userEnvironment.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmbcluster.labels" . | nindent 4 }}
---
# ClusterRole with permissions needed by the backend pod-manager to
# create and manage user environments (pods, services, pvcs).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cmbcluster.fullname" . }}-pod-manager
  labels:
    {{- include "cmbcluster.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - pods/status
  - services
  - persistentvolumeclaims
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
# Note: The original rbac1.yaml included permissions for Deployments and Ingresses.
# The current pod_manager.py does not manage these resources, so they are omitted
# for security (least privilege). Add them back if functionality changes.
---
# Binds the main backend service account to the pod-manager role.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cmbcluster.fullname" . }}-pod-manager-binding
  labels:
    {{- include "cmbcluster.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cmbcluster.fullname" . }}-pod-manager
  apiGroup: rbac.authorization.k8s.io
{{- end -}}