apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cmbcluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmbcluster.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cmbcluster.fullname" . }}-pod-manager
rules:
- apiGroups: [""]
  resources: ["pods", "services", "persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cmbcluster.fullname" . }}-binding
subjects:
- kind: ServiceAccount
  name: {{ include "cmbcluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cmbcluster.fullname" . }}-pod-manager
  apiGroup: rbac.authorization.k8s.io
