{{- if .Values.serviceAccount.create -}}
{{- $cloudProvider := .Values.global.cloudProvider | default "gcp" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmbcluster.labels" . | nindent 4 }}
  annotations:
    {{- if eq $cloudProvider "gcp" }}
    # GCP Workload Identity: Bind KSA to GSA
    iam.gke.io/gcp-service-account: {{ .Values.global.gcp.workloadIdentityEmail | default .Values.workloadIdentity.gsaEmail }}
    {{- else if eq $cloudProvider "aws" }}
    # AWS IRSA: Bind KSA to IAM Role
    eks.amazonaws.com/role-arn: {{ .Values.global.aws.roleArn }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}