apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cmbcluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.global.serviceAccount }}"
  labels:
    {{- include "cmbcluster.labels" . | nindent 4 }}
