apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmbcluster-frontend
  namespace: cmbcluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cmbcluster-frontend
  template:
    metadata:
      labels:
        app: cmbcluster-frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/cmbcluster-frontend:latest
        ports:
        - containerPort: 8501
        envFrom:
        - configMapRef:
            name: cmbcluster-config
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cmbcluster-frontend-service
  namespace: cmbcluster
spec:
  selector:
    app: cmbcluster-frontend
  ports:
  - port: 80
    targetPort: 8501
  type: ClusterIP
