version: 0.2
env:
  shell: bash
  git-credential-helper: yes

  parameter-store:
    TASKREV_BE: "/denario/production/TASKREV_BE"
    TASKREV_FE: "/denario/production/TASKREV_FE"

phases:
  build:
    on-failure: ABORT
    commands:
#      - "echo ${DOCKER_HUB_TOKEN} | docker login -u ${DOCKER_HUB_USER} --password-stdin"
      - "codepipeline/build_env.sh"
#      - "codepipeline/build_statics.sh"
      - 'rc="${?}"'
      - 'if [[ "${rc}" -ne 0 ]]; then exit "${rc}"; fi'
#      - "codepipeline/run_tests.sh"
#      - 'rc="${?}"'
#      - 'if [[ "${rc}" -ne 0 ]]; then exit "${rc}"; fi'
      - "codepipeline/build_docker.sh"
      - "exit ${rc}"
  post_build:
    commands:
       - bash -c "if [[ ${CODEBUILD_BUILD_SUCCEEDING} -eq 0 ]]; then exit 1; fi"
       - "codepipeline/push_docker.sh production"
       - "codepipeline/build_appspec_be.sh production"
       - "aws codepipeline start-pipeline-execution --name denario-production-${BranchName}-fe"
artifacts:
  files:
    - "appspec.yaml"
