# Default values for cmbcluster.
# This is a YAML-formatted file.

global:
  projectId: "your-gcp-project-id"
  domain: "cmbcluster.example.com"

# Workload Identity configuration
workloadIdentity:
  # The email of the Google Service Account to be impersonated by the pods.
  # This is set by the deploy.sh script.
  gsaEmail: ""

# Kubernetes Service Account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  name: "cmbcluster-ksa"

backend:
  image:
    repository: gcr.io/your-gcp-project-id/cmbcluster-backend
    tag: "latest"
    pullPolicy: IfNotPresent

frontend:
  image:
    repository: gcr.io/your-gcp-project-id/cmbcluster-frontend
    tag: "latest"
    pullPolicy: IfNotPresent

userEnvironment:
  image:
    repository: gcr.io/your-gcp-project-id/cmbcluster-user-env
    tag: "latest"
    pullPolicy: IfNotPresent