# Default values for cmbcluster.
# This is a YAML-formatted file.

global:
  projectId: "your-gcp-project-id"
  registryUrl: "us-central1-docker.pkg.dev/your-gcp-project-id/cmbcluster-images"
  imageTag: "latest"

# Workload Identity configuration
workloadIdentity:
  # The email of the Google Service Account to be impersonated by the pods.
  # This is set by the deploy.sh script.
  gsaEmail: ""

# Kubernetes Service Account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  name: "cmbcluster-ksa"

backend:
  service:
    type: ClusterIP
    port: 8000
    targetPort: http
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/your-gcp-project-id/cmbcluster-images/cmbcluster-backend
    tag: "latest"
    pullPolicy: Always
  config:
    apiUrl: "http://api.cmbagent.cloud"
    frontendUrl: "http://cmbagent.cloud"
    googleClientId: ""
    jwtAlgorithm: "HS256"
    tokenExpireHours: 8
    maxInactiveHours: 4
    maxUserPods: 1
    devMode: false
    debug: false
  # The name of the Kubernetes secret containing sensitive environment variables
  # like SECRET_KEY and GOOGLE_CLIENT_SECRET, created by deploy.sh.
  secretName: "cmbcluster-backend-secrets"
  resources: {}

ingress:
  enabled: true
  className: "nginx"
  # The cert-manager ClusterIssuer to use for TLS certificates.
  clusterIssuer: "letsencrypt-prod"
  annotations:
    {}
  # The base domain for the application.
  baseDomain: "cmbagent.cloud"

  tls:
    enabled: true
    # The name of the secret for the main application (e.g., cmbcluster.local, api.cmbcluster.local)
    mainSecretName: "cmbcluster-main-tls"
    # The name of the secret for the wildcard user environments (e.g., *.cmbcluster.local)
    usersSecretName: "cmbcluster-users-wildcard-tls"

frontend:
  service:
    type: ClusterIP
    port: 8501
    targetPort: nextjs
  image:
    repository: us-central1-docker.pkg.dev/your-gcp-project-id/cmbcluster-images/cmbcluster-frontend
    tag: "latest"
    pullPolicy: Always
  replicaCount: 1
  resources: {}

userEnvironment:
  image:
    repository: us-central1-docker.pkg.dev/your-gcp-project-id/cmbcluster-images/cmbcluster-user-env
    tag: "latest"
    pullPolicy: Always
  serviceAccount:
    # The name of the low-privilege service account for user-created pods.
    name: "cmbcluster-user-sa"